### ISSUE TITLE
还有在更新吗？

### ISSUE THREAD

**Issue by 1876538694** [liesauer/Unity-debugging-dlls#1]
比如:2021版本的

**Comment by liesauer** [comment]
这个备份本人并不维护更新，你可以试试以下方案

https://github.com/dnSpyEx/dnSpy/issues/10
https://github.com/dnSpyEx/dnSpy/issues/167
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2552#issuecomment-1025482713
